#include <stdlib.h>

const char *content_nibble_table[256] = {
	[0x00] = NULL, // "Undefined content",
	[0x01] = NULL, // "Undefined content",
	[0x02] = NULL, // "Undefined content",
	[0x03] = NULL, // "Undefined content",
	[0x04] = NULL, // "Undefined content",
	[0x05] = NULL, // "Undefined content",
	[0x06] = NULL, // "Undefined content",
	[0x07] = NULL, // "Undefined content",
	[0x08] = NULL, // "Undefined content",
	[0x09] = NULL, // "Undefined content",
	[0x0a] = NULL, // "Undefined content",
	[0x0b] = NULL, // "Undefined content",
	[0x0c] = NULL, // "Undefined content",
	[0x0d] = NULL, // "Undefined content",
	[0x0e] = NULL, // "Undefined content",
	[0x0f] = NULL, // "Undefined content",

	// Movie/Drama
	[0x10] = "Movie/Drama (general)",
	[0x11] = "Movie/Drama - detective/thriller",
	[0x12] = "Movie/Drama - adventure/western/war",
	[0x13] = "Movie/Drama - science fiction/fantasy/horror",
	[0x14] = "Movie/Drama - comedy",
	[0x15] = "Movie/Drama - soap/melodrama/folkloric",
	[0x16] = "Movie/Drama - romance",
	[0x17] = "Movie/Drama - serious/classical/religious/historical movie/drama",
	[0x18] = "Movie/Drama - adult movie/drama",
	[0x19] = "Movie/Drama - reserved for future use",
	[0x1a] = "Movie/Drama - reserved for future use",
	[0x1b] = "Movie/Drama - reserved for future use",
	[0x1c] = "Movie/Drama - reserved for future use",
	[0x1d] = "Movie/Drama - reserved for future use",
	[0x1e] = "Movie/Drama - reserved for future use",
	[0x1f] = "\0Movie/Drama - user defined",

	// News/Current affairs
	[0x21] = "News/Current affairs (general)",
	[0x22] = "News/Current affairs - news/weather report",
	[0x23] = "News/Current affairs - news magazine",
	[0x24] = "News/Current affairs - documentary",
	[0x25] = "News/Current affairs - discussion/interview/debate",
	[0x26] = "News/Current affairs - reserved for future use",
	[0x27] = "News/Current affairs - reserved for future use",
	[0x28] = "News/Current affairs - reserved for future use",
	[0x29] = "News/Current affairs - reserved for future use",
	[0x2a] = "News/Current affairs - reserved for future use",
	[0x2b] = "News/Current affairs - reserved for future use",
	[0x2c] = "News/Current affairs - reserved for future use",
	[0x2d] = "News/Current affairs - reserved for future use",
	[0x2e] = "News/Current affairs - reserved for future use",
	[0x2f] = "\0News/Current affairs - user defined",

	// Show/Game show
	[0x30] = "Show/Game show (general)",
	[0x31] = "Show/Game show - game show/quiz/contest",
	[0x32] = "Show/Game show - variety show",
	[0x33] = "Show/Game show - talk show",
	[0x34] = "Show/Game show - reserved for future use",
	[0x35] = "Show/Game show - reserved for future use",
	[0x36] = "Show/Game show - reserved for future use",
	[0x37] = "Show/Game show - reserved for future use",
	[0x38] = "Show/Game show - reserved for future use",
	[0x39] = "Show/Game show - reserved for future use",
	[0x3a] = "Show/Game show - reserved for future use",
	[0x3b] = "Show/Game show - reserved for future use",
	[0x3c] = "Show/Game show - reserved for future use",
	[0x3d] = "Show/Game show - reserved for future use",
	[0x3e] = "Show/Game show - reserved for future use",
	[0x3f] = "\0Show/Game show - user defined",

	// Sports
	[0x40] = "Sports (general)",
	[0x41] = "Sports - special events (Olympic Games, World Cup, etc.)",
	[0x42] = "Sports - sports magazines",
	[0x43] = "Sports - football/soccer",
	[0x44] = "Sports - tennis/squash",
	[0x45] = "Sports - team sports (excluding football)",
	[0x46] = "Sports - athletics",
	[0x47] = "Sports - motor sport",
	[0x48] = "Sports - water sport",
	[0x49] = "Sports - winter sports",
	[0x4a] = "Sports - equestrian",
	[0x4b] = "Sports - martial sports",
	[0x4c] = "Sports - reserved for future use",
	[0x4d] = "Sports - reserved for future use",
	[0x4e] = "Sports - reserved for future use",
	[0x4f] = "\0Sports - user defined",

	// Children's/Youth programmes
	[0x50] = "Children's/Youth programmes (general)",
	[0x51] = "Children's/Youth programmes - pre-school children's programmes",
	[0x52] = "Children's/Youth programmes - entertainment programmes for 6 to 14",
	[0x53] = "Children's/Youth programmes - entertainment programmes for 10 to 16",
	[0x54] = "Children's/Youth programmes - informational/educational/school programmes",
	[0x55] = "Children's/Youth programmes - cartoons/puppets",
	[0x56] = "Children's/Youth programmes - reserved for future use",
	[0x57] = "Children's/Youth programmes - reserved for future use",
	[0x58] = "Children's/Youth programmes - reserved for future use",
	[0x59] = "Children's/Youth programmes - reserved for future use",
	[0x5a] = "Children's/Youth programmes - reserved for future use",
	[0x5b] = "Children's/Youth programmes - reserved for future use",
	[0x5c] = "Children's/Youth programmes - reserved for future use",
	[0x5d] = "Children's/Youth programmes - reserved for future use",
	[0x5e] = "Children's/Youth programmes - reserved for future use",
	[0x5f] = "\0Children's/Youth programmes - user defined",

	// Music/Ballet/Dance
	[0x60] = "Music/Ballet/Dance (general)",
	[0x61] = "Music/Ballet/Dance - rock/pop",
	[0x62] = "Music/Ballet/Dance - serious music/classical music",
	[0x63] = "Music/Ballet/Dance - folk/traditional music",
	[0x64] = "Music/Ballet/Dance - jazz",
	[0x65] = "Music/Ballet/Dance - musical/opera",
	[0x66] = "Music/Ballet/Dance - ballet",
	[0x67] = "Music/Ballet/Dance - reserved for future use",
	[0x68] = "Music/Ballet/Dance - reserved for future use",
	[0x69] = "Music/Ballet/Dance - reserved for future use",
	[0x6a] = "Music/Ballet/Dance - reserved for future use",
	[0x6b] = "Music/Ballet/Dance - reserved for future use",
	[0x6c] = "Music/Ballet/Dance - reserved for future use",
	[0x6d] = "Music/Ballet/Dance - reserved for future use",
	[0x6e] = "Music/Ballet/Dance - reserved for future use",
	[0x6f] = "\0Music/Ballet/Dance - user defined",

	// Arts/Culture (without music)
	[0x70] = "Arts/Culture (without music) (general)",
	[0x71] = "Arts/Culture (without music) - performing arts",
	[0x72] = "Arts/Culture (without music) - fine arts",
	[0x73] = "Arts/Culture (without music) - religion",
	[0x74] = "Arts/Culture (without music) - popular culture/traditional arts",
	[0x75] = "Arts/Culture (without music) - literature",
	[0x76] = "Arts/Culture (without music) - film/cinema",
	[0x77] = "Arts/Culture (without music) - experimental film/video",
	[0x78] = "Arts/Culture (without music) - broadcasting/press",
	[0x79] = "Arts/Culture (without music) - new media",
	[0x7a] = "Arts/Culture (without music) - arts/culture magazines",
	[0x7b] = "Arts/Culture (without music) - fashion",
	[0x7c] = "Arts/Culture (without music) - reserved for future use",
	[0x7d] = "Arts/Culture (without music) - reserved for future use",
	[0x7e] = "Arts/Culture (without music) - reserved for future use",
	[0x7f] = "\0Arts/Culture (without music) - user defined",

	// Social/Political issues/Economics
	[0x80] = "Social/Political issues/Economics (general)",
	[0x81] = "Social/Political issues/Economics - magazines/reports/documentary",
	[0x82] = "Social/Political issues/Economics - economics/social advisory",
	[0x83] = "Social/Political issues/Economics - remarkable people",
	[0x84] = "Social/Political issues/Economics - reserved for future use",
	[0x85] = "Social/Political issues/Economics - reserved for future use",
	[0x86] = "Social/Political issues/Economics - reserved for future use",
	[0x87] = "Social/Political issues/Economics - reserved for future use",
	[0x88] = "Social/Political issues/Economics - reserved for future use",
	[0x89] = "Social/Political issues/Economics - reserved for future use",
	[0x8a] = "Social/Political issues/Economics - reserved for future use",
	[0x8b] = "Social/Political issues/Economics - reserved for future use",
	[0x8c] = "Social/Political issues/Economics - reserved for future use",
	[0x8d] = "Social/Political issues/Economics - reserved for future use",
	[0x8e] = "Social/Political issues/Economics - reserved for future use",
	[0x8f] = "\0Social/Political issues/Economics - user defined",

	// Education/Science/Factual topics
	[0x90] = "Education/Science/Factual topics (general)",
	[0x91] = "Education/Science/Factual topics - nature/animals/environment",
	[0x92] = "Education/Science/Factual topics - technology/natural sciences",
	[0x93] = "Education/Science/Factual topics - medicine/physiology/psychology",
	[0x94] = "Education/Science/Factual topics - foreign countries/expeditions",
	[0x95] = "Education/Science/Factual topics - social/spiritual sciences",
	[0x96] = "Education/Science/Factual topics - further education",
	[0x97] = "Education/Science/Factual topics - languages",
	[0x98] = "Education/Science/Factual topics - reserved for future use",
	[0x99] = "Education/Science/Factual topics - reserved for future use",
	[0x9a] = "Education/Science/Factual topics - reserved for future use",
	[0x9b] = "Education/Science/Factual topics - reserved for future use",
	[0x9c] = "Education/Science/Factual topics - reserved for future use",
	[0x9d] = "Education/Science/Factual topics - reserved for future use",
	[0x9e] = "Education/Science/Factual topics - reserved for future use",
	[0x9f] = "\0Education/Science/Factual topics - user defined",

	// Leisure hobbies
	[0xa0] = "Leisure hobbies (general)",
	[0xa1] = "Leisure hobbies - tourism/travel",
	[0xa2] = "Leisure hobbies - handicraft",
	[0xa3] = "Leisure hobbies - motoring",
	[0xa4] = "Leisure hobbies - fitness and health",
	[0xa5] = "Leisure hobbies - cooking",
	[0xa6] = "Leisure hobbies - advertizement/shopping",
	[0xa7] = "Leisure hobbies - gardening",
	[0xa8] = "Leisure hobbies - reserved for future use",
	[0xa9] = "Leisure hobbies - reserved for future use",
	[0xaa] = "Leisure hobbies - reserved for future use",
	[0xab] = "Leisure hobbies - reserved for future use",
	[0xac] = "Leisure hobbies - reserved for future use",
	[0xad] = "Leisure hobbies - reserved for future use",
	[0xae] = "Leisure hobbies - reserved for future use",
	[0xaf] = "\0Leisure hobbies - user defined",

	// Special characteristics
	[0xb0] = "Special characteristics - original language",
	[0xb1] = "Special characteristics - black and white",
	[0xb2] = "Special characteristics - unpublished",
	[0xb3] = "Special characteristics - live broadcast",
	[0xb4] = "Special characteristics - reserved for future use",
	[0xb5] = "Special characteristics - reserved for future use",
	[0xb6] = "Special characteristics - reserved for future use",
	[0xb7] = "Special characteristics - reserved for future use",
	[0xb8] = "Special characteristics - reserved for future use",
	[0xb9] = "Special characteristics - reserved for future use",
	[0xba] = "Special characteristics - reserved for future use",
	[0xbb] = "Special characteristics - reserved for future use",
	[0xbc] = "Special characteristics - reserved for future use",
	[0xbd] = "Special characteristics - reserved for future use",
	[0xbe] = "Special characteristics - reserved for future use",
	[0xbf] = "\0Special characteristics - user defined",

	// Reserved for future use
	[0xc0] = "Reserved for future use",
	[0xc1] = "Reserved for future use",
	[0xc2] = "Reserved for future use",
	[0xc3] = "Reserved for future use",
	[0xc4] = "Reserved for future use",
	[0xc5] = "Reserved for future use",
	[0xc6] = "Reserved for future use",
	[0xc7] = "Reserved for future use",
	[0xc8] = "Reserved for future use",
	[0xc9] = "Reserved for future use",
	[0xca] = "Reserved for future use",
	[0xcb] = "Reserved for future use",
	[0xcc] = "Reserved for future use",
	[0xcd] = "Reserved for future use",
	[0xce] = "Reserved for future use",
	[0xcf] = "Reserved for future use",

	[0xd0] = "Reserved for future use",
	[0xd1] = "Reserved for future use",
	[0xd2] = "Reserved for future use",
	[0xd3] = "Reserved for future use",
	[0xd4] = "Reserved for future use",
	[0xd5] = "Reserved for future use",
	[0xd6] = "Reserved for future use",
	[0xd7] = "Reserved for future use",
	[0xd8] = "Reserved for future use",
	[0xd9] = "Reserved for future use",
	[0xda] = "Reserved for future use",
	[0xdb] = "Reserved for future use",
	[0xdc] = "Reserved for future use",
	[0xdd] = "Reserved for future use",
	[0xde] = "Reserved for future use",
	[0xdf] = "Reserved for future use",

	[0xe0] = "Reserved for future use",
	[0xe1] = "Reserved for future use",
	[0xe2] = "Reserved for future use",
	[0xe3] = "Reserved for future use",
	[0xe4] = "Reserved for future use",
	[0xe5] = "Reserved for future use",
	[0xe6] = "Reserved for future use",
	[0xe7] = "Reserved for future use",
	[0xe8] = "Reserved for future use",
	[0xe9] = "Reserved for future use",
	[0xea] = "Reserved for future use",
	[0xeb] = "Reserved for future use",
	[0xec] = "Reserved for future use",
	[0xed] = "Reserved for future use",
	[0xee] = "Reserved for future use",
	[0xef] = "Reserved for future use",

	// User defined
	[0xf0] = "\0User defined",
	[0xf1] = "\0User defined",
	[0xf2] = "\0User defined",
	[0xf3] = "\0User defined",
	[0xf4] = "\0User defined",
	[0xf5] = "\0User defined",
	[0xf6] = "\0User defined",
	[0xf7] = "\0User defined",
	[0xf8] = "\0User defined",
	[0xf9] = "\0User defined",
	[0xfa] = "\0User defined",
	[0xfb] = "\0User defined",
	[0xfc] = "\0User defined",
	[0xfd] = "\0User defined",
	[0xfe] = "\0User defined",
	[0xff] = "\0User defined",
};
